// automatically generated by arduino-cmake
#line 1 "/Users/aefreedman/Documents/CLionProjects/Servo_0/Servo_0.ino"
#include <Arduino.h>
#include <Servo.h>

#line 6 "/Users/aefreedman/Documents/CLionProjects/Servo_0/Servo_0_Servo_0.ino.cpp"
#include "Arduino.h"

//=== START Forward: /Users/aefreedman/Documents/CLionProjects/Servo_0/Servo_0.ino
 void setup() ;
 void setup() ;
 void loop() ;
 void loop() ;
//=== END Forward: /Users/aefreedman/Documents/CLionProjects/Servo_0/Servo_0.ino
#line 2 "/Users/aefreedman/Documents/CLionProjects/Servo_0/Servo_0.ino"


Servo servoMotor;
int servoPin = 3;

void setup() {
    Serial.begin(9600);
    servoMotor.attach(servoPin);
}

void loop() {
    int analogValue = analogRead(A0);
    Serial.println(analogValue);

    int servoAngle = map(analogValue, 0, 1023, 0, 179);
    servoMotor.write(analogValue);
}